@Fireforce_HostAddress = https://localhost:7122/api

GET {{Fireforce_HostAddress}}/department/get/
Accept: application/json
###
GET {{Fireforce_HostAddress}}/department/4/
Accept: application/json
###
DELETE {{Fireforce_HostAddress}}/department/4/delete/
Accept: application/json
###
POST {{Fireforce_HostAddress}}/department/add/
Content-Type: application/json
{
  "voivodeship": "Mazowieckie",
  "postalCode": "05555",
  "street": "Jasna",
  "bnumber": 1
}
###